sched/fair: Fix unused prefer_idle variable in enqueue_task_fair
kernel/sched/fair.c:5443:7: error: unused variable 'prefer_idle'
  [-Werror,-Wunused-variable]
 5443 |         bool prefer_idle = sched_feat(EAS_PREFER_IDLE) ?

Signed-off-by: FelcoX <parbindarsingh@outlook.com>